package-lock.json
package.json

Performs a `lint:fix` on all staged `.ts?(x)`-files before commit

chore: add husky precommit hook

---

src/api.d.ts
src/components/cases/CaseDetail.tsx
src/components/cases/CaseDetailHeader.tsx
src/components/global/FraudProbability.tsx
src/components/itineraries/DraggableItineraryItem.tsx
src/components/itineraries/ItineraryItem.tsx
src/components/search/SearchResult.tsx
src/components/search/SearchResultCase.tsx
src/components/search/SearchResultPlural.tsx
src/components/search/SearchResultSingle.tsx
src/lib/groupCasesByAddress.ts
src/state/useParse.ts
src/state/useSearch.ts

Display fraud probability on itinerary items, search results, suggestions and case details

Add fraud probability

---

.eslintrc.js

Add linting rules:
```
"space-unary-ops": ["error"],          // ok: i++, not ok: i ++;
"space-infix-ops": ["error"],          // ok: i = 1, not ok: i=1
"block-spacing": ["error", "always"] . // ok: function foo() { return true; } not ok: function foo() {return true;}
```

chore: add linting rules

---

src/api.d.ts
src/components/itineraries/DraggableItineraryItem.tsx
src/components/itineraries/SpinnerCheckbox.tsx
src/contexts/StateContext.ts
src/state.d.ts
src/state/itinerariesReducer.ts
src/state/useItineraries.ts

Adds checkboxes to itineray items

feat: add itinerary checkboxes

---

src/lib/itineraryToCases.ts

Only add addresses that are not checked, to the google map

feat: only add addresses that are not checked in the google map

---

src/api.d.ts
src/state/useSearch.ts

Cast possibly null to undefined

Fix for possibly null fraud_prediction

---

src/components/itineraries/Generate.tsx
src/state/useItineraries.ts

feat: post start-address to backend

---

src/components/itineraries/Generate.tsx

Changed button-type from primary to textButton.

chore: change remove-start-adres-button to textButton

---

src/state/useItineraries.ts

Remove timeOut, and actually sync with the backend

feat: sync checked status with backend

---

src/components/global/IconButton.tsx
src/components/search/itinerary/ItinerarySearchResultButtons.tsx
src/react.d.ts

- add event stopPropagation calls
- add type "button" to IconButton

Chrome Android click area flash

---

src/components/itineraries/Generate/Generate.tsx
src/components/itineraries/ItineraryTeamMembers.tsx
src/components/itineraries/TeamFields.tsx
src/components/itineraries/TeamMemberFields.tsx

1. Split 'team member fields' into its own component: `TeamMemberFields`
2. Refactored `ItineraryTeamMembers` to make use of final-form and the new `TeamMemberFields` component

Refactor: implement final-form in ItineraryTeamMembers component

---

src/components/search/ClearButton.tsx
src/components/search/SearchForm.tsx

Implement final-form in search-form.

refactor: implement final-form in search-form

---

src/components/cases/CaseDetail.tsx
src/components/cases/CaseDetailHeader.tsx
src/components/cases/FraudPrediction/FraudPredictionDetails.tsx
src/components/cases/FraudPrediction/FraudPredictionDetailsModal.tsx
src/components/cases/FraudPrediction/ShapValue.tsx
src/components/cases/FraudPrediction/utils/parseShapValues.ts
src/types/api.d.ts

Adds the first version of a shap-value details modal.

feat: add shap-value modal

---

src/components/form-components/validators/isNotIntersectingWith.ts
src/components/planning/DayPartSettings.tsx

excludedStadia and primaryStadium cannot intersect

fix: validators in daypart settings

---

src/components/atoms/Box/Box.tsx
src/components/search/SearchForm.tsx

refactor: refactored search-form to use amsterdam-react-final-form

---

src/components/auth/AuthSession.tsx
src/components/auth/Logout.tsx
src/components/cases/AnonymousToggle.tsx
src/components/itineraries/DraggableItineraryItem.tsx
src/components/itineraries/DroppableItinerary.tsx
src/components/itineraries/Generate/Generate.tsx
src/components/itineraries/Itinerary.tsx
src/components/itineraries/ItineraryTeamMembers.tsx
src/components/notes/NoteForm.tsx
src/components/notes/Notes.tsx
src/components/planning/Settings.tsx
src/components/providers/StateProvider/StateProvider.tsx
src/components/providers/StateProvider/useCreateGlobalState.tsx
src/components/search/Issues.tsx
src/components/search/SearchForm.tsx
src/components/search/Suggestions.tsx
src/components/search/itinerary/ItinerarySearchResultButtons.tsx
src/contexts/StateContextValue.d.ts
src/hooks/useGlobalActions.ts
src/pages/LoginCallbackPage.tsx

Be careful. Also ran `npm run lint:fix`

Split up useGlobalState and useGlobalActions

---

src/components/itineraries/Generate/Generate.tsx
src/components/notes/Notes.tsx
src/components/planning/Settings.tsx
src/components/search/Issues.tsx
src/components/search/Search.tsx
src/components/search/Suggestions.tsx

Removed separately defined spinners, as spinner is now defined on page level

Removed separately defined spinners

---

package-lock.json
package.json

Versioning

---

src/app/features/itineraries/components/molecules/Buttons/Buttons.tsx
src/app/features/itineraries/components/molecules/DeleteItineraryItemButton/DeleteItineraryItemButton.tsx
src/app/features/itineraries/components/organisms/TeamMemberForm/TeamMemberForm.tsx
src/app/features/itineraries/components/pages/create/CreateItineraryPage.tsx
src/app/features/itineraries/components/pages/itinerary/ItineraryPage.tsx
src/app/features/itineraries/components/pages/itinerary/mapItineraryItem.tsx
src/app/features/itineraries/components/pages/list/ListItinerariesPage.tsx
src/app/features/itineraries/components/pages/open-issues/OpenIssuesPage.tsx
src/app/features/itineraries/utils/mapCaseToCardProps.tsx
src/app/features/shared/components/form/AddressPicker/components/StartAddressSearchResults/StartAddressSearchResults.tsx
src/app/features/shared/components/molecules/ItineraryItemCard/ItineraryItemCard.stories.tsx
src/app/features/shared/components/molecules/ItineraryItemCard/ItineraryItemCard.tsx
src/app/features/shared/components/molecules/ItineraryNavigationButton/ItineraryNavigationButton.tsx
src/app/features/shared/components/molecules/OpenIssuesNavigationButton/OpenIssuesNavigationButton.tsx
src/app/features/visits/components/organisms/NoteWizard/NoteWizard.tsx
src/app/state/rest/custom/useItinerary.ts
src/app/state/rest/hooks/useApiCache.ts
src/app/state/rest/hooks/useApiRequest.ts
src/app/state/rest/index.ts
src/app/state/rest/provider/noopContext.ts

- Navigation is not cleared but updated
- Itinerary list is not cleared but updated. Which introduces a more fluid delete action

Feature: opt-in for using a stale cache

---

package-lock.json
package.json

- Uninstall `@dtsgenerator/replace-namespace`

Uninstall replace-namespace

---

package-lock.json
package.json

Fixes npm peer-dependency warnings

chore: bump version amsterdam-react-final-form

---

src/App.tsx
src/app/features/shared/components/layouts/DefaultLayout/DefaultLayout.tsx
src/app/features/shared/components/organisms/ErrorDisplay/ErrorDisplay.tsx
src/app/state/error/ErrorProvider.tsx
src/app/state/rest/hooks/utils/utils.ts

feat: prettier error handling

---

package-lock.json
package.json

https://github.com/typicode/husky/issues/639

Downgrade husky to prevent skipping Git hooks in GUIs

---

src/app/features/cases/components/atoms/Hr/Hr.tsx
src/app/features/cases/components/atoms/Label/Label.tsx
src/app/features/cases/components/atoms/Value/InvalidValue.tsx
src/app/features/cases/components/molecules/MailtoAnchor/MailtoAnchor.tsx
src/app/features/cases/components/organisms/CaseDetail/CaseDetailSection.tsx
src/app/features/cases/components/organisms/CaseDetail/CaseDetailSectionStyles.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/General.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Logbook.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/RelatedCases.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Residence.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Residents.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Scratchpad.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Signal.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/Stadia.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/VacationRental.tsx
src/app/features/cases/components/organisms/CaseDetail/sections/VacationRentalThisYear.tsx
src/app/features/cases/email/basisInformatie.ts
src/app/features/login/components/pages/login/AuthPage.tsx
src/app/features/shared/components/form/ShowHide/ShowHide.stories.tsx
src/app/features/shared/components/molecules/DefinitionList/DefinitionList.tsx
src/app/features/shared/components/molecules/Purified/Purified.tsx

Use CSS Grid. Improve whitespace and copy. Improve ‘kladblok’ entry display.

Improve values grid of case detail page

---

src/app/features/itineraries/components/organisms/ItineraryForm/ItineraryForm.tsx
src/app/features/shared/components/form/UniqueDropdown/UniqueDropdown.tsx

Remove temporarily unused code

---

src/app/features/cases/components/organisms/CaseDetail/CaseDetail.tsx
src/app/features/cases/components/organisms/CaseDetail/CaseDetailSectionStyles.ts

Distribute case detail sections over multiple columns

---

src/app/features/itineraries/components/pages/itinerary/ItineraryPage.tsx

This is a regression from 4b4f0d6b1369fbe4dcc3db05f09b78fbf2790c71

Included visited addresses when copying itinerary items

---

src/app/features/shared/components/form/ShowHide/ShowHide.tsx

Copy of https://github.com/Amsterdam/zaken-frontend/pull/846

Reset value when field is hidden

---

src/app/features/itineraries/utils/mapCaseToCardProps.tsx
src/app/features/shared/components/molecules/ItineraryItemCard/ItineraryItemCard.tsx

Serach results is an illogical place to delete a case from the itinerary. Cases can be removed on the itinerary page.

Disallow deleting search result from itinerary

---

src/app/features/settings/components/organisms/Days/CreateDaySettingsForm.tsx
src/app/features/settings/components/organisms/Days/CreateDaySettingsFormV2.tsx
src/app/features/settings/components/organisms/Days/DaySettingsForm.tsx
src/app/features/settings/components/organisms/Days/DaySettingsFormV2.tsx

Should have been removed with efc6fc166d625f7a01f45dbffb1bb846214e129a

Remove obsolete layout hack
